"""add_index_on_site_id

Revision ID: 8fa1c3f97e07
Revises: 96ebd9652b7a
Create Date: 2026-07-05 01:20:43.264157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa1c3f97e07'
down_revision: Union[str, Sequence[str], None] = '96ebd9652b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('websites_site_id_key'), 'websites', type_='unique')
    op.create_index(op.f('ix_websites_site_id'), 'websites', ['site_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websites_site_id'), table_name='websites')
    op.create_unique_constraint(op.f('websites_site_id_key'), 'websites', ['site_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
