"""add_site_id_to_websites

Revision ID: 96ebd9652b7a
Revises: bbe218a84d09
Create Date: 2026-07-05 01:10:55.772284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ebd9652b7a'
down_revision: Union[str, Sequence[str], None] = 'bbe218a84d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('site_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'websites', ['site_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'websites', type_='unique')
    op.drop_column('websites', 'site_id')
    # ### end Alembic commands ###
