export const products = [
  {
    id: "studio-headphones",
    name: "Studio Pro Headphones",
    category: "Audio",
    price: 249,
    rating: 4.8,
    reviews: 1284,
    badge: "Best seller",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    description: "Closed-back wireless headphones with active noise cancellation and a 42-hour battery.",
  },
  {
    id: "canvas-weekender",
    name: "Canvas Weekender Bag",
    category: "Travel",
    price: 138,
    rating: 4.7,
    reviews: 846,
    badge: "New",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
    description: "Water-resistant canvas duffel with leather handles, shoe storage, and laptop sleeve.",
  },
  {
    id: "ceramic-planter",
    name: "Ceramic Desk Planter",
    category: "Home",
    price: 32,
    rating: 4.6,
    reviews: 319,
    badge: "Limited",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=900&q=80",
    description: "Hand-glazed planter sized for succulents, herbs, and small indoor greenery.",
  },
  {
    id: "running-shoes",
    name: "AeroRun Knit Shoes",
    category: "Footwear",
    price: 119,
    rating: 4.5,
    reviews: 1051,
    badge: "Popular",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    description: "Lightweight daily trainers with breathable knit uppers and responsive cushioning.",
  },
  {
    id: "smart-watch",
    name: "PulseTrack Smart Watch",
    category: "Wearables",
    price: 199,
    rating: 4.7,
    reviews: 2106,
    badge: "Top rated",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    description: "Fitness watch with GPS, sleep analytics, heart monitoring, and seven-day battery life.",
  },
  {
    id: "espresso-maker",
    name: "Compact Espresso Maker",
    category: "Kitchen",
    price: 289,
    rating: 4.4,
    reviews: 674,
    badge: "Deal",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
    description: "Countertop espresso machine with steam wand, pressure gauge, and fast heat-up.",
  },
  {
    id: "linen-shirt",
    name: "Washed Linen Shirt",
    category: "Apparel",
    price: 72,
    rating: 4.6,
    reviews: 543,
    badge: "New colors",
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=900&q=80",
    description: "Soft garment-washed linen shirt tailored for warm weather and everyday layering.",
  },
  {
    id: "desk-lamp",
    name: "Arc LED Desk Lamp",
    category: "Office",
    price: 84,
    rating: 4.8,
    reviews: 731,
    badge: "Low stock",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
    description: "Dimmable metal desk lamp with warm-to-cool lighting and a weighted base.",
  },
  {
    id: "yoga-mat",
    name: "GripFlow Yoga Mat",
    category: "Fitness",
    price: 58,
    rating: 4.7,
    reviews: 1490,
    badge: "Best seller",
    image: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=900&q=80",
    description: "Non-slip natural rubber mat with alignment marks and extra joint support.",
  },
  {
    id: "sunglasses",
    name: "Polarized City Sunglasses",
    category: "Accessories",
    price: 96,
    rating: 4.5,
    reviews: 387,
    badge: "UV400",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80",
    description: "Acetate-frame sunglasses with polarized lenses and compact travel case.",
  },
  {
    id: "mechanical-keyboard",
    name: "Tactile Mechanical Keyboard",
    category: "Tech",
    price: 154,
    rating: 4.9,
    reviews: 1988,
    badge: "Editor pick",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
    description: "Compact hot-swappable keyboard with tactile switches and programmable keys.",
  },
  {
    id: "wool-throw",
    name: "Merino Wool Throw",
    category: "Home",
    price: 124,
    rating: 4.6,
    reviews: 478,
    badge: "Cozy",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=900&q=80",
    description: "Fine merino throw blanket with a brushed finish and modern woven pattern.",
  },
  {
    id: "travel-mug",
    name: "Insulated Travel Mug",
    category: "Kitchen",
    price: 34,
    rating: 4.7,
    reviews: 2409,
    badge: "Leakproof",
    image: "https://images.unsplash.com/photo-1649769560353-4951d1c0e38d?auto=format&fit=crop&w=900&q=80",
    description: "Double-wall stainless mug that keeps drinks hot for eight hours or cold all day.",
  },
  {
    id: "leather-wallet",
    name: "Slim Leather Wallet",
    category: "Accessories",
    price: 68,
    rating: 4.8,
    reviews: 966,
    badge: "RFID",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80",
    description: "Low-profile full-grain leather wallet with RFID lining and quick-access slots.",
  },
  {
    id: "air-purifier",
    name: "QuietRoom Air Purifier",
    category: "Home",
    price: 216,
    rating: 4.6,
    reviews: 872,
    badge: "HEPA",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80",
    description: "HEPA air purifier for bedrooms and offices with quiet night mode and sensor display.",
  },
  {
    id: "chef-knife",
    name: "Eight-Inch Chef Knife",
    category: "Kitchen",
    price: 112,
    rating: 4.9,
    reviews: 1360,
    badge: "Pro grade",
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=900&q=80",
    description: "Balanced forged chef knife with a stainless blade and comfortable pakkawood handle.",
  },
  {
    id: "denim-jacket",
    name: "Classic Denim Jacket",
    category: "Apparel",
    price: 98,
    rating: 4.5,
    reviews: 733,
    badge: "Restocked",
    image: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=900&q=80",
    description: "Midweight denim jacket with a relaxed fit, antique hardware, and deep pockets.",
  },
  {
    id: "bluetooth-speaker",
    name: "Trail Mini Speaker",
    category: "Audio",
    price: 79,
    rating: 4.6,
    reviews: 1654,
    badge: "Waterproof",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80",
    description: "Rugged portable speaker with rich bass, IP67 protection, and stereo pairing.",
  },
  {
    id: "camera-bag",
    name: "Modular Camera Sling",
    category: "Travel",
    price: 142,
    rating: 4.7,
    reviews: 512,
    badge: "Creator pick",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80",
    description: "Padded camera sling with movable dividers and fast side access for daily shoots.",
  },
  {
    id: "skincare-set",
    name: "Daily Skincare Set",
    category: "Beauty",
    price: 64,
    rating: 4.4,
    reviews: 1168,
    badge: "Clean",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
    description: "Three-step skincare routine with cleanser, vitamin serum, and lightweight moisturizer.",
  },
  {
    id: "standing-desk",
    name: "LiftPro Standing Desk",
    category: "Office",
    price: 429,
    rating: 4.8,
    reviews: 603,
    badge: "Ergonomic",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=900&q=80",
    description: "Electric sit-stand desk with memory presets, cable tray, and a durable laminate top.",
  },
  {
    id: "hydration-pack",
    name: "Summit Hydration Pack",
    category: "Outdoor",
    price: 88,
    rating: 4.6,
    reviews: 444,
    badge: "Trail ready",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    description: "Compact hiking pack with a two-liter reservoir, airflow back panel, and rain cover.",
  },
  {
    id: "wireless-charger",
    name: "Foldable Wireless Charger",
    category: "Tech",
    price: 59,
    rating: 4.5,
    reviews: 937,
    badge: "3-in-1",
    image: "https://images.unsplash.com/photo-1615526675159-e248c3021d3f?auto=format&fit=crop&w=900&q=80",
    description: "Travel-ready magnetic charger for phone, watch, and earbuds with USB-C power.",
  },
  {
    id: "cast-iron-pan",
    name: "Seasoned Cast Iron Pan",
    category: "Kitchen",
    price: 48,
    rating: 4.8,
    reviews: 2751,
    badge: "Durable",
    image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    description: "Pre-seasoned skillet for searing, baking, and camp cooking on any heat source.",
  },
  {
    id: "linen-bedding",
    name: "Cooling Linen Bedding",
    category: "Home",
    price: 186,
    rating: 4.7,
    reviews: 695,
    badge: "Breathable",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    description: "Stonewashed linen sheet set with a soft texture that gets better with every wash.",
  },
  {
    id: "trail-jacket",
    name: "Packable Rain Jacket",
    category: "Outdoor",
    price: 132,
    rating: 4.6,
    reviews: 581,
    badge: "Weatherproof",
    image: "https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=900&q=80",
    description: "Lightweight shell jacket with sealed seams, pit vents, and a stowable hood.",
  },
  {
    id: "notebook-set",
    name: "Dot Grid Notebook Set",
    category: "Office",
    price: 24,
    rating: 4.5,
    reviews: 340,
    badge: "Set of 3",
    image: "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80",
    description: "Lay-flat notebooks with premium dot grid paper for planning, sketching, and notes.",
  },
  {
    id: "perfume",
    name: "Cedar Citrus Eau de Parfum",
    category: "Beauty",
    price: 118,
    rating: 4.4,
    reviews: 492,
    badge: "Signature",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80",
    description: "Fresh citrus opening with warm cedar, amber, and soft musk in the drydown.",
  },
  {
    id: "gaming-mouse",
    name: "Precision Gaming Mouse",
    category: "Tech",
    price: 86,
    rating: 4.8,
    reviews: 1882,
    badge: "Fast",
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80",
    description: "Low-latency wireless mouse with optical switches, adjustable DPI, and long battery life.",
  },
  {
    id: "bike-helmet",
    name: "Urban Bike Helmet",
    category: "Outdoor",
    price: 74,
    rating: 4.7,
    reviews: 621,
    badge: "MIPS",
    image: "https://images.unsplash.com/photo-1558611848-73f7eb4001a1?auto=format&fit=crop&w=900&q=80",
    description: "Commuter helmet with integrated rear light, ventilation, and a secure dial fit.",
  },
];
